### ISSUE TITLE
_check_url function doesn't use login credentials

### ISSUE THREAD

**Issue by talcloudshare** [jhermann/artifactory-debian#6]
When there's a changes file, it results in:

D: webdav: Checking URL '...changes'
webdav: FATAL: Overwriting existing changes at '...changes' not allowed: HTTP Error 401: Unauthorized

**Comment by talcloudshare** [comment]
http://stackoverflow.com/questions/635113/python-urllib2-basic-http-authentication-and-tr-im

Looks like 1st answer could easily solve the issue

**Comment by talcloudshare** [comment]
I don't have push permissions, but this should do the trick:

`    trace("Checking URL '%(url)s'", url=url)
    try:
        request = urllib2.Request(url)
        request.add_header("Authorization", 'Basic %s' % login.encode('base64').replace('\n', '').strip())
        with closing(urllib2.urlopen(request)) as handle:`

**Comment by jhermann** [comment]
Thanks for reporting, that one escaped since we allow anon reads.

**Comment by jhermann** [comment]
There was actually a TODO marker for this in the code. :smirk_cat:

**Comment by jhermann** [comment]
@talcloudshare please check this works for you.

**Comment by jhermann** [comment]
Fixed in v1.3.3
